// Code generated by op-codegen - DO NOT EDIT

package onepassword

import (
	"github.com/1password/onepassword-sdk-go/internal"
)

// Client represents an instance of the 1Password Go SDK client.
type Client struct {
	config internal.ClientConfig
	Items  ItemsSource
	Vaults VaultsSource
}

func initAPIs(client *Client, inner internal.InnerClient) {
	client.Items = *NewItemsSource(inner)
	client.Vaults = *NewVaultsSource(inner)
}
