// AUTOGENERATED - DO NOT EDIT MANUALLY
package onepassword

import (
	"context"
	"encoding/json"

	"github.com/1password/onepassword-sdk-go/internal"
)

type ItemsAPI interface {
	GetById(ctx context.Context, vaultId string, itemId string) (Item, error)
}

type ItemsSource struct {
	internal.InnerClient
}

func NewItemsSource(inner internal.InnerClient) *ItemsSource {
	return &ItemsSource{inner}
}

func (s ItemsSource) GetById(ctx context.Context, vaultId string, itemId string) (Item, error) {

	resultString, err := clientInvoke(ctx, s.InnerClient, "GetById", map[string]interface{}{
		"vault_id": vaultId,
		"item_id":  itemId,
	})
	if err != nil {
		return Item{}, err
	}
	var result Item
	err = json.Unmarshal([]byte(*resultString), &result)
	if err != nil {
		return Item{}, err
	}
	return result, nil
}
