// Code generated by op-codegen - DO NOT EDIT

package onepassword

import (
	"context"
	"encoding/json"

	"github.com/1password/onepassword-sdk-go/internal"
)

// client.Items.Secrets.Resolve(...)
type ItemsSecretsSource struct {
	internal.InnerClient
}

func NewItemsSecretsSource(inner internal.InnerClient) *ItemsSecretsSource {
	return &ItemsSecretsSource{inner}
}

// Resolve returns the secret the provided secret reference points to.
func (s ItemsSecretsSource) Resolve(ctx context.Context, secretReference string) (string, error) {
	resultString, err := clientInvoke(ctx, s.InnerClient, "SecretsResolve", map[string]interface{}{
		"secret_reference": secretReference,
	})
	if err != nil {
		return "", err
	}
	var result string
	err = json.Unmarshal([]byte(*resultString), &result)
	if err != nil {
		return "", err
	}
	return result, nil
}
