// AUTOGENERATED - DO NOT EDIT MANUALLY
package onepassword

import (
	"context"
	"encoding/json"

	"github.com/1password/onepassword-sdk-go/internal"
)

type ReportsAPI interface {
	GetAccountOverview(ctx context.Context) (string, error)
}

type ReportsSource struct {
	internal.InnerClient
}

func NewReportsSource(inner internal.InnerClient) *ReportsSource {
	return &ReportsSource{inner}
}

func (s ReportsSource) GetAccountOverview(ctx context.Context) (string, error) {

	resultString, err := clientInvoke(ctx, s.InnerClient, "GetAccountOverview", map[string]interface{}{})
	if err != nil {
		return "", err
	}
	var result string
	err = json.Unmarshal([]byte(*resultString), &result)
	if err != nil {
		return "", err
	}
	return result, nil
}
