// AUTOGENERATED - DO NOT EDIT MANUALLY
package onepassword

import (
	"context"
	"encoding/json"

	"github.com/1password/onepassword-sdk-go/internal"
)

type ReportsAPI interface {
	GetAccountOverview(ctx context.Context) (AccountOverview, error)
	GetDevicesOverview(ctx context.Context) (DevicesOverview, error)
}

type ReportsSource struct {
	internal.InnerClient
}

func NewReportsSource(inner internal.InnerClient) *ReportsSource {
	return &ReportsSource{inner}
}

func (s ReportsSource) GetAccountOverview(ctx context.Context) (AccountOverview, error) {

	resultString, err := clientInvoke(ctx, s.InnerClient, "GetAccountOverview", map[string]interface{}{})
	if err != nil {
		return AccountOverview{}, err
	}
	var result AccountOverview
	err = json.Unmarshal([]byte(*resultString), &result)
	if err != nil {
		return AccountOverview{}, err
	}
	return result, nil
}

func (s ReportsSource) GetDevicesOverview(ctx context.Context) (DevicesOverview, error) {

	resultString, err := clientInvoke(ctx, s.InnerClient, "GetDevicesOverview", map[string]interface{}{})
	if err != nil {
		return DevicesOverview{}, err
	}
	var result DevicesOverview
	err = json.Unmarshal([]byte(*resultString), &result)
	if err != nil {
		return DevicesOverview{}, err
	}
	return result, nil
}
