// AUTOGENERATED - DO NOT EDIT MANUALLY
package onepassword

import (
	"context"
	"encoding/json"

	"github.com/1password/onepassword-sdk-go/internal"
)

type SecretsAPI interface {
	Resolve(ctx context.Context, secretReference string) (string, error)
}

type SecretsSource struct {
	internal.InnerClient
}

func NewSecretsSource(inner internal.InnerClient) *SecretsSource {
	return &SecretsSource{inner}
}

func (s SecretsSource) Resolve(ctx context.Context, secretReference string) (string, error) {

	resultString, err := clientInvoke(ctx, s.InnerClient, "Resolve", map[string]interface{}{
		"secret_reference": secretReference,
	})
	if err != nil {
		return "", err
	}
	var result string
	err = json.Unmarshal([]byte(*resultString), &result)
	if err != nil {
		return "", err
	}
	return result, nil
}
