// Code generated by typeshare 1.9.0. DO NOT EDIT.
package onepassword

type AccountOverview struct {
	UserCount  uint32 `json:"user_count"`
	GroupCount uint32 `json:"group_count"`
	VaultCount uint32 `json:"vault_count"`
}
