// Code generated by op-codegen - DO NOT EDIT

package onepassword

import (
	"context"
	"encoding/json"

	"github.com/1password/onepassword-sdk-go/internal"
)

type VaultsAPI interface {
	ListAll(ctx context.Context) (*Iterator[VaultOverview], error)
}

// The Vaults API holds all the operations the SDK client can perform on 1Password vaults.
type VaultsSource struct {
	innerClient internal.InnerClient
}

func NewVaultsSource(inner internal.InnerClient) VaultsAPI {
	return &VaultsSource{innerClient: inner}
}

// List all vaults
func (v VaultsSource) ListAll(ctx context.Context) (*Iterator[VaultOverview], error) {
	resultString, err := clientInvoke(ctx, v.innerClient, "VaultsListAll", map[string]interface{}{})
	if err != nil {
		return nil, err
	}
	var result []VaultOverview
	err = json.Unmarshal([]byte(*resultString), &result)
	if err != nil {
		return nil, err
	}
	return NewIterator(result), nil
}
