// Code generated by op-codegen - DO NOT EDIT

package onepassword

import (
	"context"
	"encoding/json"

	"github.com/1password/onepassword-sdk-go/internal"
)

// The Vaults API holds all the operations the SDK client can perform on 1Password vaults.
type VaultsAPI interface {
	// List information about vaults that's configurable based on some input parameters.
	List(ctx context.Context, params ...VaultListParams) ([]VaultOverview, error)

	GetOverview(ctx context.Context, vaultUuid string) (VaultOverview, error)

	Get(ctx context.Context, vaultUuid string, vaultParams VaultGetParams) (Vault, error)

	GrantGroupPermissions(ctx context.Context, vaultID string, groupPermissionsList []GroupAccess) error

	UpdateGroupPermissions(ctx context.Context, groupPermissionsList []GroupVaultAccess) error

	RevokeGroupPermissions(ctx context.Context, vaultID string, groupID string) error
}

type VaultsSource struct {
	internal.InnerClient
}

func NewVaultsSource(inner internal.InnerClient) VaultsAPI {
	return &VaultsSource{InnerClient: inner}
}

// List information about vaults that's configurable based on some input parameters.
func (v VaultsSource) List(ctx context.Context, params ...VaultListParams) ([]VaultOverview, error) {
	var param VaultListParams
	if len(params) > 0 {
		param = params[0]
	}
	resultString, err := clientInvoke(ctx, &v.InnerClient, "VaultsList", map[string]interface{}{
		"params": param,
	})
	if err != nil {
		return nil, err
	}
	var result []VaultOverview
	err = json.Unmarshal([]byte(*resultString), &result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

func (v VaultsSource) GetOverview(ctx context.Context, vaultUuid string) (VaultOverview, error) {
	resultString, err := clientInvoke(ctx, &v.InnerClient, "VaultsGetOverview", map[string]interface{}{
		"vault_uuid": vaultUuid,
	})
	if err != nil {
		return VaultOverview{}, err
	}
	var result VaultOverview
	err = json.Unmarshal([]byte(*resultString), &result)
	if err != nil {
		return VaultOverview{}, err
	}
	return result, nil
}

func (v VaultsSource) Get(ctx context.Context, vaultUuid string, vaultParams VaultGetParams) (Vault, error) {
	resultString, err := clientInvoke(ctx, &v.InnerClient, "VaultsGet", map[string]interface{}{
		"vault_uuid":   vaultUuid,
		"vault_params": vaultParams,
	})
	if err != nil {
		return Vault{}, err
	}
	var result Vault
	err = json.Unmarshal([]byte(*resultString), &result)
	if err != nil {
		return Vault{}, err
	}
	return result, nil
}

func (v VaultsSource) GrantGroupPermissions(ctx context.Context, vaultID string, groupPermissionsList []GroupAccess) error {
	_, err := clientInvoke(ctx, &v.InnerClient, "VaultsGrantGroupPermissions", map[string]interface{}{
		"vault_id":               vaultID,
		"group_permissions_list": groupPermissionsList,
	})
	return err
}

func (v VaultsSource) UpdateGroupPermissions(ctx context.Context, groupPermissionsList []GroupVaultAccess) error {
	_, err := clientInvoke(ctx, &v.InnerClient, "VaultsUpdateGroupPermissions", map[string]interface{}{
		"group_permissions_list": groupPermissionsList,
	})
	return err
}

func (v VaultsSource) RevokeGroupPermissions(ctx context.Context, vaultID string, groupID string) error {
	_, err := clientInvoke(ctx, &v.InnerClient, "VaultsRevokeGroupPermissions", map[string]interface{}{
		"vault_id": vaultID,
		"group_id": groupID,
	})
	return err
}
