name: Notify about PR ready for review

on:
  # Run this workflow from the target branch. We do this because GitHub doesn't allow reading secrets from forked PRs
  # source branch, and it would cause problems for PRs opened by dependabot.
  pull_request_target:
    branches: ["main"]
    types: [ opened, ready_for_review ]

jobs:
  slackNotification:
    name: Slack Notification
    if: github.event.pull_request.user.login == 'dependabot[bot]' # This step only runs when PR is opened by dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Slack Notification
        uses: kv109/action-ready-for-review@76820bc668c3ce6c9be0c9322d07c2d8804dbd7a
        env:
          SLACK_CHANNEL: sdk-security-alerts
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
