name: Notify about PR ready for review

on:
  pull_request:
    branches: ["main"]
    types: [ opened, ready_for_review ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  slackNotification:
    name: Slack Notification
    if: startsWith(github.head_ref, 'dependabot/') # This step only runs when PR has dependabot/ HEAD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Slack Notification
        uses: kv109/action-ready-for-review@0.2
        env:
          SLACK_CHANNEL: sdk-security-alerts
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}